apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: sonarqube-scan
  namespace: cicd
spec:
  params:
    - name: SONAR_HOST_URL
      type: string
    - name: SONAR_PROJECT_KEY
      type: string
  workspaces:
    - name: source
  steps:
    - name: sonar-scan
      image: sonarsource/sonar-scanner-cli:5.0
      workingDir: $(workspaces.source.path)
      env:
        - name: SONAR_TOKEN
          valueFrom:
            secretKeyRef:
              name: sonar-credentials
              key: sonar-token
      script: |
        #!/busybox/sh
        set -e
        sonar-scanner \
          -Dsonar.host.url=$(params.SONAR_HOST_URL) \
          -Dsonar.projectKey=$(params.SONAR_PROJECT_KEY) \
          -Dsonar.token=$SONAR_TOKEN \
          -Dsonar.qualitygate.wait=true
