# Profile Activation (Defaults to 'dev')
spring.profiles.active=

# Application Identity
spring.application.name=quickshop

# JPA / Hibernate Common Settings
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.batch_size=25
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Actuator Base Settings
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=when_authorized
management.info.env.enabled=true
