apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-push-template
  namespace: cicd
spec:
  params:
    - name: git-repo-url
    - name: git-revision
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: ci-cd-pipeline-run-
        namespace: cicd
      spec:
        serviceAccountName: pipeline-sa
        pipelineRef:
          name: ci-cd-pipeline
        params:
          - name: repo-url
            value: $(tt.params.git-repo-url)
          - name: revision
            value: $(tt.params.git-revision)
          - name: image
            value: docker.io/<your-dockerhub-user>/devops-demo-app:$(tt.params.git-revision)
          - name: sonar-host-url
            value: https://sonarcloud.io
          - name: sonar-project-key
            value: my-org_devops-pipeline-demo
        workspaces:
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: shared-workspace-pvc
